    name: CI workflow

    on:
      push:
        branches: [ "main" ]
      pull_request:
        branches: [ "main" ]

    jobs:
      build:
        runs-on: ubuntu-latest
        container: python:3.9-slim
        steps:
          - name: 1-Checkout
            uses: actions/checkout@v3

          - name: 2-Install dependencies
            run: |
              python -m pip install --upgrade pip  
              pip install -r requirements.txt

          - name: 3-Lint with flake8
            run: |
              flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
              flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

          - name: 4-Unit tests with nose
            run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app